services:
  main:
    build: .
    container_name: border_scraper_telegram_bot
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro